// Freenove_IR_Remote_Keycode.h

#ifndef _FREENOVE_IR_REMOTE_KEYCODE_h
#define _FREENOVE_IR_REMOTE_KEYCODE_h

#if defined(ARDUINO) && ARDUINO >= 100
	#include "arduino.h"
#else
	#include "WProgram.h"
#endif

#include <IRremote.h>

#define IR_REMOTE_KEYCODE_POWER		0xFFA25D
#define IR_REMOTE_KEYCODE_MENU		0xFF629D
#define IR_REMOTE_KEYCODE_MUTE		0xFFE21D

#define IR_REMOTE_KEYCODE_MODE		0xFF22DD
#define IR_REMOTE_KEYCODE_UP		  0xFF02FD
#define IR_REMOTE_KEYCODE_BACK		0xFFC23D

#define IR_REMOTE_KEYCODE_LEFT		0xFFE01F
#define IR_REMOTE_KEYCODE_CENTER	0xFFA857
#define IR_REMOTE_KEYCODE_RIGHT		0xFF906F

#define IR_REMOTE_KEYCODE_0			  0xFF6897
#define IR_REMOTE_KEYCODE_DOWN		0xFF9867
#define IR_REMOTE_KEYCODE_OK		  0xFFB04F

#define IR_REMOTE_KEYCODE_1			0xFF30CF
#define IR_REMOTE_KEYCODE_2			0xFF18E7
#define IR_REMOTE_KEYCODE_3			0xFF7A85

#define IR_REMOTE_KEYCODE_4			0xFF10EF
#define IR_REMOTE_KEYCODE_5			0xFF38C7
#define IR_REMOTE_KEYCODE_6			0xFF5AA5

#define IR_REMOTE_KEYCODE_7			0xFF42BD
#define IR_REMOTE_KEYCODE_8			0xFF4AB5
#define IR_REMOTE_KEYCODE_9			0xFF52AD


#endif
